name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3.5.3

      - name: 🟢 Use Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run Vitest with coverage
        run: npm run coverage

      - name: 📤 Upload coverage report
        uses: actions/upload-pages-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: 🔼 Upload to Coveralls
        run: npm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
